### ISSUE TITLE
SSHX error: "export: (admin): bad variable name"

### ISSUE THREAD

**Issue by Sarke** [cronicle-edge/cronicle-edge#168]
```
cronicle-1  | [1735800979.542][2025-01-02 01:56:19][manager1][7][Cronicle][debug][5][Job completed with error][params: {"ssh_host":"root@10.0.0.219","kill_cmd":"pkill -s $$","script":"echo \"Running SSHX job on $HOSTNAME\"","json":0,"trunc_var":0,"annotate":0,"target_os":"linux","lang":"shell","theme":"default"} | timeout: 0 | catch_up: 0 | queue_max: 1000 | timezone: America/Vancouver | plugin: sshxplug | silent: 0 | concurrent_arg: 0 | graph_icon:  | args:  | category: cm58zm69y02 | target: allgrp | algo: random | multiplex: 0 | stagger: 0 | options: [object Object] | start_time: null | end_time: null | interval: false | interval_start: false | retries: 0 | retry_delay: 0 | detached: 0 | queue: 0 | chain:  | chain_error:  | notify_success:  | notify_fail:  | web_hook:  | web_hook_start:  | web_hook_error: 0 | cpu_limit: 0 | cpu_sustain: 0 | memory_limit: 0 | memory_sustain: 0 | log_max_size: 0 | notes:  | tty: 0 | debug_sudo: 0 | now: 1735800977 | source: Manual (admin) | id: jm5ez31th02 | time_start: 1735800977.141 | hostname: manager1 | event: em5ey9iad0f | event_title: Job1 | plugin_title: SSHX | is_wf: undefined | category_title: ATC | nice_target: All Servers | ipc: true | lag: 4 | stdin: false | stdin_script: undefined | last_exit_code: 2 | last_memo: undefined | state: undefined | command: node bin/sshx-plugin.js | log_file: /opt/cronicle/logs/jobs/jm5ez31th02.log | pid: 59 | log_file_size: 136 | complete: 1 | code: 2 | description: Script exited with code: 2; sh: 50: export: (admin): bad variable name]
cronicle-1  | [1735800979.542][2025-01-02 01:56:19][manager1][7][Cronicle][debug][6][Storing job log: /opt/cronicle/logs/jobs/jm5ez31th02.log: jobs/jm5ez31th02/log.txt.gz][]
cronicle-1  | [1735800979.542][2025-01-02 01:56:19][manager1][7][Error][error][job][Job failed: jm5ez31th02][params: {"ssh_host":"root@10.0.0.219","kill_cmd":"pkill -s $$","script":"echo \"Running SSHX job on $HOSTNAME\"","json":0,"trunc_var":0,"annotate":0,"target_os":"linux","lang":"shell","theme":"default"} | timeout: 0 | catch_up: 0 | queue_max: 1000 | timezone: America/Vancouver | plugin: sshxplug | silent: 0 | concurrent_arg: 0 | graph_icon:  | args:  | category: cm58zm69y02 | target: allgrp | algo: random | multiplex: 0 | stagger: 0 | options: [object Object] | start_time: null | end_time: null | interval: false | interval_start: false | retries: 0 | retry_delay: 0 | detached: 0 | queue: 0 | chain:  | chain_error:  | notify_success:  | notify_fail:  | web_hook:  | web_hook_start:  | web_hook_error: 0 | cpu_limit: 0 | cpu_sustain: 0 | memory_limit: 0 | memory_sustain: 0 | log_max_size: 0 | notes:  | tty: 0 | debug_sudo: 0 | now: 1735800977 | source: Manual (admin) | id: jm5ez31th02 | time_start: 1735800977.141 | hostname: manager1 | event: em5ey9iad0f | event_title: Job1 | plugin_title: SSHX | is_wf: undefined | category_title: ATC | nice_target: All Servers | ipc: true | lag: 4 | stdin: false | stdin_script: undefined | last_exit_code: 2 | last_memo: undefined | state: undefined | command: node bin/sshx-plugin.js | log_file: /opt/cronicle/logs/jobs/jm5ez31th02.log | pid: 59 | log_file_size: 375 | complete: 1 | code: 2 | description: Script exited with code: 2; sh: 50: export: (admin): bad variable name | time_end: 1735800979.542 | elapsed: 2.4010000228881836]
```

---

EDIT: nicer to look at:

```json
{
    "ssh_host": "root@10.0.0.219",
    "kill_cmd": "pkill -s $$",
    "script": "echo \"Running SSHX job on $HOSTNAME\"",
    "json": 0,
    "trunc_var": 0,
    "annotate": 0,
    "target_os": "linux",
    "lang": "shell",
    "theme": "default"
}
```

```yml
timeout: 0
catch_up: 0
queue_max: 1000
timezone: America/Vancouver
plugin: sshxplug
silent: 0
concurrent_arg: 0
graph_icon: 
args: 
category: cm58zm69y02
target: allgrp
algo: random
multiplex: 0
stagger: 0
options: [object Object]
start_time: null
end_time: null
interval: false
interval_start: false
retries: 0
retry_delay: 0
detached: 0
queue: 0
chain: 
chain_error: 
notify_success: 
notify_fail: 
web_hook: 
web_hook_start: 
web_hook_error: 0
cpu_limit: 0
cpu_sustain: 0
memory_limit: 0
memory_sustain: 0
log_max_size: 0
notes: 
tty: 0
debug_sudo: 0
now: 1735800977
source: Manual (admin)
id: jm5ez31th02
time_start: 1735800977.141
hostname: manager1
event: em5ey9iad0f
event_title: Job1
plugin_title: SSHX
is_wf: undefined
category_title: ATC
nice_target: All Servers
ipc: true
lag: 4
stdin: false
stdin_script: undefined
last_exit_code: 2
last_memo: undefined
state: undefined
command: node bin/sshx-plugin.js
log_file: /opt/cronicle/logs/jobs/jm5ez31th02.log
pid: 59
log_file_size: 375
complete: 1
code: 2
description: Script exited with code: 2; sh: 50: export: (admin): bad variable name
time_end: 1735800979.542
elapsed: 2.4010000228881836
```
