### ISSUE TITLE
Doc - simplest scenario in a Docker environment with docker compose / sqlite

### ISSUE THREAD

**Issue by scls19fr** [cronicle-edge/cronicle-edge#95]
Hello,

I'm trying to move from [ofelia](https://github.com/mcuadros/ofelia) / [chadburn](https://github.com/PremoWeb/chadburn) to a more "advanced" job scheduler with a crontab like interface and with a web UI to see how jobs have been executed.

I'm looking for help for the simplest scenario in a Docker environment (ideally with docker compose) and SQLite storage (I looked at #92 )

I want manager run periodically a command inside of a new container, using a specific image (what ofelia calls a `job-run`... not to be confound with `job-exec`).

My first problem is that changing cronicle image to cronicle-edge raised this message


```
$ docker compose up
[+] Running 1/0
 ✔ Container cronicle  Created                                                                                                                                                                                                          0.0s
Attaching to cronicle
cronicle  | tini (tini version 0.19.0)
cronicle  | Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version
cronicle  |
cronicle  | Execute a program under the supervision of a valid init process (tini)
cronicle  |
cronicle  | Command line options:
cronicle  |
cronicle  |   --version: Show version and exit.
cronicle  |   -h: Show this help message and exit.
cronicle  |   -s: Register as a process subreaper (requires Linux >= 3.4).
cronicle  |   -p SIGNAL: Trigger SIGNAL when parent dies, e.g. "-p SIGKILL".
cronicle  |   -v: Generate more verbose output. Repeat up to 3 times.
cronicle  |   -w: Print a warning when processes are getting reaped.
cronicle  |   -g: Send signals to the child's process group.
cronicle  |   -e EXIT_CODE: Remap EXIT_CODE (from 0 to 255) to 0.
cronicle  |   -l: Show license and exit.
cronicle  |
cronicle  | Environment variables:
cronicle  |
cronicle  |   TINI_SUBREAPER: Register as a process subreaper (requires Linux >= 3.4).
cronicle  |   TINI_VERBOSITY: Set the verbosity level (default: 1).
cronicle  |   TINI_KILL_PROCESS_GROUP: Send signals to the child's process group.
cronicle  |
cronicle  |
cronicle exited with code 
```

My `docker-compose.yml` looks like (behind Traefik)

```yaml
version: "3.8"

services:
  cronicle:
    image: ghcr.io/cronicle-edge/cronicle-edge:v1.7.0
    container_name: cronicle
    restart: unless-stopped  # always
    # expose:
    #  - 3012
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.cronicle.entrypoints=websecure"
      - "traefik.http.routers.cronicle.rule=Host(`cronicle.domain.net`)"
      - "traefik.http.routers.cronicle.tls=true"
      - "traefik.http.routers.cronicle.tls.certresolver=default"
      - "traefik.http.services.cronicle.loadbalancer.server.port=3012"


    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock  #:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf/config.json:/opt/cronicle/conf/config.json
      - data:/opt/cronicle/data
      - logs:/opt/cronicle/logs
      - plugins:/opt/cronicle/plugins

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3

    networks:
      - web

volumes:
  data:
  logs:
  plugins:

networks:
  web:
    external: true
```

I must admit that I have no idea what `tini` is

Some help will be very nice.
